import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './nav/Navbar'
import ToasterProvider from './providers/ToasterProvider'
import SignalRProvider from './providers/SignalRProvider'
import { getCurrentUser } from './actions/authActions'
import AppSidebar from './appsidebar/AppSidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const user = await getCurrentUser();
  return (
    <html lang="en">
      <head>      
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link href="https://fonts.googleapis.com/css2?family=Grape+Nuts&family=Mynerve&family=Waiting+for+the+Sunrise&display=swap" rel="stylesheet" />
      </head>

      <body className={inter.className}>
        <ToasterProvider />
        <Navbar />
        <main className='container mx-auto pt-10'>
          <SignalRProvider user={user}>
            <div className='grid grid-cols-6 gap-4'>
              <div>
                <div className='col-span-1 sticky top-36'>
                    <AppSidebar />
                </div>
              </div>
              
              <div className='col-span-5 mt-2'>
                  {children}
              </div>       
            </div>       
          </SignalRProvider>

          <footer className="bg-white rounded-lg shadow dark:bg-gray-900 m-4">
              <div className="w-full max-w-screen-xl mx-auto p-4 md:py-8">
                <hr className="my-6 border-gray-200 sm:mx-auto dark:border-gray-700 lg:my-8" />
                <span className="block text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2024 <a href="https://messages365.net/" className="hover:underline">Kenneth Cheung™</a>. All Rights Reserved.</span>
              </div>
          </footer>
        </main>
      </body>
    </html>
  )
}




